return {
	Title = "我全都要",
	Author = "jiliangsui",
	Version = "1.0.0.8",
	GameVersion = "1.0.46.0",
	Description = "不定期更新。\n\nv1.0.0 功能描述：\n开局特质无限\n8类物品重量独立开关\n五行锁定混元（仅太吾）\n自定义开局点数（主属性/技艺/功法/特质，滑条调节）。\n\n下个版本计划：增加功法突破成功率。",
	Cover = "cover.png",
	FrontendPlugins = {
		[1] = "GrantAllTraitsMod.dll",
	},
	BackendPlugins = {
		[1] = "GrantAllTraitsMod.dll",
	},
	TagList = {
		[1] = "Modifications",
		[2] = "Optimizations",
		[3] = "Compatible Mods",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "Enabled",
			DisplayName = "开局特质无限",
			Description = "开启后开局特质选择不再受点数限制",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "BookWeightEnabled",
			DisplayName = "书籍重量为0",
			Description = "开启后新获取的书籍重量变为0",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "FoodWeightEnabled",
			DisplayName = "食物重量为0",
			Description = "开启后食物重量变为0",
			DefaultValue = false,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "MedicineWeightEnabled",
			DisplayName = "药物茶酒重量为0",
			Description = "开启后药物和茶酒重量变为0",
			DefaultValue = false,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "EquipmentWeightEnabled",
			DisplayName = "装备重量为0",
			Description = "开启后武器、护甲、饰品、衣物、载具重量变为0",
			DefaultValue = false,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "ToolWeightEnabled",
			DisplayName = "工具重量为0",
			Description = "开启后工具重量变为0",
			DefaultValue = false,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "MaterialWeightEnabled",
			DisplayName = "材料重量为0",
			Description = "开启后材料重量变为0",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "MiscWeightEnabled",
			DisplayName = "杂项重量为0",
			Description = "开启后杂项重量变为0",
			DefaultValue = false,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "CricketWeightEnabled",
			DisplayName = "促织重量为0",
			Description = "开启后促织重量变为0",
			DefaultValue = false,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "LockFiveElementsToMix",
			DisplayName = "五行锁定混元",
			Description = "开启后角色先天五行锁定为混元",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "BreakthroughAlwaysSuccess",
			DisplayName = "突破百分百成功",
			Description = "开启后功法突破每次必定成功",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Slider",
			Key = "CustomPointMainAttribute",
			DisplayName = "主属性总点数",
			Description = "默认300",
			MinValue = 300,
			MaxValue = 540,
			StepSize = 1,
			DefaultValue = 423,
		},
		[12] = {
			SettingType = "Slider",
			Key = "CustomPointLifeSkill",
			DisplayName = "技艺资质总点数",
			Description = "默认800",
			MinValue = 800,
			MaxValue = 1440,
			StepSize = 1,
			DefaultValue = 1094,
		},
		[13] = {
			SettingType = "Slider",
			Key = "CustomPointCombatSkill",
			DisplayName = "功法资质总点数",
			Description = "默认700",
			MinValue = 700,
			MaxValue = 1260,
			StepSize = 1,
			DefaultValue = 910,
		},
		[14] = {
			SettingType = "Slider",
			Key = "CustomPointFeature",
			DisplayName = "特质总点数",
			Description = "默认7，特性共30个",
			MinValue = 7,
			MaxValue = 90,
			StepSize = 1,
			DefaultValue = 40,
		},
	},
	ChangeConfig = true,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	Source = 0,
	FileId = 3756287820,
	WorkshopCover = "cover.png",
	Visibility = 0,
	UpdateLogList = { },
}
