return {
	Title = "我全都要",
	Author = "jiliangsui",
	Version = "1.0.0.8",
	GameVersion = "1.0.46.0",
	Description = "不定期更新。\n\n功能：开局特质无限、7类物品重量独立开关、五行锁定混元（仅太吾）、自定义开局点数（主属性/技艺/功法/特质，滑条调节）、突破百分百成功。",
	Cover = "cover.png",
	FrontendPlugins = {
		[1] = "GrantAllTraitsMod.dll",
	},
	BackendPlugins = {
		[1] = "GrantAllTraitsMod.dll",
	},
	TagList = {
		[1] = "Modifications",
		[2] = "Optimizations",
		[3] = "Compatible Mods",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "Enabled",
			DisplayName = "开局特质无限",
			Description = "开启后开局特质选择不再受点数限制",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "BookWeightEnabled",
			DisplayName = "书籍重量为0",
			Description = "开启后书籍重量变为0",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "FoodWeightEnabled",
			DisplayName = "食物重量为0",
			Description = "开启后食物（含茶酒）重量变为0",
			DefaultValue = true,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "MedicineWeightEnabled",
			DisplayName = "药毒重量为0",
			Description = "开启后药物重量变为0",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "EquipmentWeightEnabled",
			DisplayName = "装备重量为0",
			Description = "开启后兵器、宝物、衣装、家畜重量变为0",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "ToolWeightEnabled",
			DisplayName = "工具重量为0",
			Description = "开启后工具重量变为0",
			DefaultValue = true,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "MaterialWeightEnabled",
			DisplayName = "材料重量为0",
			Description = "开启后材料重量变为0",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "OtherWeightEnabled",
			DisplayName = "其他重量为0",
			Description = "开启后杂项、促织等重量变为0",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "LockFiveElementsToMix",
			DisplayName = "五行锁定混元",
			Description = "开启后太吾本人的五行强制为混元",
			DefaultValue = true,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "BreakthroughAlwaysSuccess",
			DisplayName = "突破百分百成功",
			Description = "开启后功法突破每次必定成功",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Slider",
			Key = "CustomPointMainAttribute",
			DisplayName = "主属性总点数",
			Description = "默认300",
			MinValue = 300,
			MaxValue = 540,
			StepSize = 1,
			DefaultValue = 300,
		},
		[12] = {
			SettingType = "Slider",
			Key = "CustomPointLifeSkill",
			DisplayName = "技艺资质总点数",
			Description = "默认800",
			MinValue = 800,
			MaxValue = 1440,
			StepSize = 1,
			DefaultValue = 800,
		},
		[13] = {
			SettingType = "Slider",
			Key = "CustomPointCombatSkill",
			DisplayName = "功法资质总点数",
			Description = "默认700",
			MinValue = 700,
			MaxValue = 1260,
			StepSize = 1,
			DefaultValue = 700,
		},
		[14] = {
			SettingType = "Slider",
			Key = "CustomPointFeature",
			DisplayName = "特质总点数",
			Description = "默认7",
			MinValue = 7,
			MaxValue = 90,
			StepSize = 1,
			DefaultValue = 7,
		},
	},
	ChangeConfig = true,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	Source = 0,
	FileId = 3,
	Visibility = 0,
	UpdateLogList = { },
}
